name: 'assets-push-action'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  file:
    required: true
    description: '同步的配置文件'
  ignore:
    description: 'ignore'
    required: false
    default: '[]'
runs:
  using: 'node16'
  main: 'dist/index.js'
